language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --verbose --testsuite=flysystem-azure-tests

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml

matrix:
  fast_finish: true
